name: gallery_media_picker_plus
description: "A modern, customizable Flutter media picker for images and videos with multi-pick and album browsing."
version: 1.0.1
homepage: https://github.com/Pritom-Shajed/gallery_media_picker
repository: https://github.com/Pritom-Shajed/gallery_media_picker
issue_tracker: https://github.com/Pritom-Shajed/gallery_media_picker/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  oktoast: ^3.4.0
  photo_manager: ^3.7.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^8.0.0

example: example/